apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-v3
  namespace: dev-kafka-test
spec:
  serviceName: kafka-v3
  replicas: 1
  selector:
    matchLabels:
      app: kafka-v3
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka-v3
    spec:
      nodeSelector:
        rfpool: lab
      initContainers:
        - name: agent
          image: ftidevacr.azurecr.io/ops/jmx-exporter-agent:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: exporter-agent
              mountPath: /exporter-agent
      containers:
        - name: kafka-v3
          env:
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms1G -Xmx1G"
            - name: KAFKA_ARGS
              value: "--override zookeeper.connect=zookeeper-0.zookeeper:2181 --override log.retention.bytes=45000000000 --override log.retention.hours=168"
            - name: KAFKA_OPTS
              value: "-javaagent:/exporter-agent/jmx-exporter-agent.jar=12345:/exporter-agent/config.yaml"
          image: neowu/kafka:3.1.0
          volumeMounts:
            - name: data
              mountPath: /data
            - name: exporter-agent
              mountPath: /exporter-agent
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 3Gi
              cpu: 2
      volumes:
        - emptyDir: { }
          name: exporter-agent
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-v3
  namespace: dev-kafka-test
spec:
  clusterIP: None
  ports:
    - port: 9092
  selector:
    app: kafka-v3

